import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { AppShell, Button, Group, Header, Navbar, Title } from '@mantine/core'
import { ArrowRight } from 'phosphor-react'
import { SwitchToggle } from '@/components/ColorSwitch'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={<Navbar width={{ base: 300 }} height="calc(100% - 80px)" p="xs">{/* Navbar content */}</Navbar>}
        header={<Header height={80} p="0" m="0">
          <Group position='apart'> 
            <Title order={2}>MyNotes</Title>
            <SwitchToggle />

          </Group>
        </Header>}
        styles={(theme) => ({
          main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] },
        })}
      >

        <Button>Hello</Button>
      </AppShell>
    </>
  )
}
